### ISSUE TITLE
Renata's Salon Unique

### ISSUE THREAD

**Issue by Gr0t3Man** [11ty/11ty-community#104]
### Site URL

https://renatasalonunique.nl

### Authors (GitHub usernames)

@Gr0t3Man 

### Open Collective Username

michel-van-der-kroef

**Comment by pdehaan** [comment]
@Gr0t3Man Is this the correct GitHub username? It oddly isn't auto-linking (and [https://github.com/MichelKroef](https://github.com/MichelKroef) throws a 404 error)

**Comment by Gr0t3Man** [comment]
@pdehaan you are correct, I mixed up the twitter username and GitHub name. 
I have corrected it.
