### ISSUE TITLE
[Built with Eleventy] CelineDesign personnel website

### ISSUE THREAD

**Issue by seb-celinedesign** [11ty/11ty-community#140]
### Site URL

https://www.celinedesign.com

### Open Collective Username

celinedesign

### Super Professional Business Network CTA URL

https://www.celinedesign.com

### Super Professional Business Network Company Name

CelineDesign

**Comment by pdehaan** [comment]
@seb-celinedesign The "Source code URL" links seems to be 404ing (on this issue and I think your other issues as well).
Are the source repos all private?

**Comment by pdehaan** [comment]
Yeah, if they aren't public repos, you might need to edit the issues and revert them to "No response", otherwise I think the 11ty site will try linking to the source URL and people will end up at 404 pages.
