### ISSUE TITLE
[Built with Eleventy] My pro website and blog

### ISSUE THREAD

**Issue by tomquinonero** [11ty/11ty-community#146]
### Site URL

https://tomquinonero.com

### Open Collective Username

tomquinonero

### Super Professional Business Network CTA URL

https://tomquinonero.com/eleventy

### Super Professional Business Network Company Name

Tom Quinonero

**Comment by pdehaan** [comment]
Looks good.
Q: Is that an Eleventy site or a Nuxt.js site?

> Powered by [nuxt.js](https://github.com/nuxt/nuxt.js) and [lazysizes](https://github.com/aFarkas/lazysizes).

**Comment by tomquinonero** [comment]
@pdehaan actually, that was a Nuxt site, and the blog only was under eleventy, but I refactored it and forgot to change the footer 😭
Fixed now!
