### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by sebthom** [11ty/11ty-community#158]
### Site URL

https://vegardit.com

### Authors (GitHub usernames)

@sebthom

**Comment by pdehaan** [comment]
😍 

```html
<meta name="generator" content="Eleventy v2.0.0">
```

**Comment by sebthom** [comment]
> 😍
> 
> ```
> <meta name="generator" content="Eleventy v2.0.0">
> ```

@pdehaan  Greenfield project + curiosity 😃
