### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by Yeshwanthyk** [11ty/11ty-community#186]
### Site URL

https://www.yeshyendamuri.com/

**Comment by Yeshwanthyk** [comment]
An older portfolio I created isn't up anymore. Was wondering if it can be removed.

ref: https://github.com/11ty/11ty-community/blob/edd2e56c45b66fe69fa0c34c93e06f114429f9f6/built-with-eleventy/UJhzTqe49O.json

**Comment by pdehaan** [comment]
> An older portfolio I created isn't up anymore. Was wondering if it can be removed.
> 
> ref: [`edd2e56`/built-with-eleventy/UJhzTqe49O.json](https://github.com/11ty/11ty-community/blob/edd2e56c45b66fe69fa0c34c93e06f114429f9f6/built-with-eleventy/UJhzTqe49O.json)

Removed in https://github.com/11ty/11ty-community/pull/191

**Comment by Yeshwanthyk** [comment]
Thank you!
