### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by GeauxWeisbeck4** [11ty/11ty-community#192]
### Site URL

https://www.jambalayastack.com

### Source code URL

https://github.com/GeauxWeisbeck4/JambalayaStack

### Open Collective Username

andrew-weisbeck

### Super Professional Business Network CTA URL

https://tarheeldevstudio.com

### Super Professional Business Network Company Name

Tar Heel Dev Studio

**Comment by zachleat** [comment]
Closing as stale (for now?)
