### ISSUE TITLE
[Built with Eleventy] Mikestreety

### ISSUE THREAD

**Issue by mikestreety** [11ty/11ty-community#195]
### Site URL

https://www.mikestreety.co.uk/

### Source code URL

https://gitlab.com/mikestreety/mikestreety

**Comment by mikestreety** [comment]
I added the generator tag but have just seen my build has failed :( Need to move back to Netlify

https://twitter.com/mikestreety/status/1551830150496636929

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v1.0.1">
```
