### ISSUE TITLE
Roxo Eleventy - is a digital agency starter template

### ISSUE THREAD

**Issue by tanvirpiash** [11ty/11ty-community#200]
### Site URL

https://roxo-eleventy.staticmania.com/

### Source code URL

https://github.com/StaticMania/roxo-eleventy

### Authors (GitHub usernames)

- @StaticMania
- @tanvirpiash
- @kausarpial

**Comment by pdehaan** [comment]
@tanvirpiash I believe this starter template is already listed on the https://www.11ty.dev/docs/starter/ page.

**Comment by tanvirpiash** [comment]
I mean to update the template.
