### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by thom4parisot** [11ty/11ty-community#205]
### Site URL

https://compagnonnage-repas.org/

### Source code URL

https://framagit.org/reseau-repas/compagnonnage-repas.org/

### Authors (GitHub usernames)

@thom4parisot

### Super Professional Business Network Company Name

détour.studio

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v1.0.1">
```
