### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by andystevenson** [11ty/11ty-community#212]
### Site URL

https://westwarwicks.club

### Source code URL

https://github.com/andystevenson/wwsc.club

### Open Collective Username

andy-stevenson

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v1.0.1">
```

**Comment by andystevenson** [comment]
@pdehaan I saw the approved status 17 days ago. I expected to see my site on the 11ty leaderboard somewhere... towards the bottom :grin:! 
Did I miss a step?

**Comment by pdehaan** [comment]
@andystevenson IIRC, @zachleat manually runs the leaderboard script which I think updates https://www.11ty.dev/speedlify/.

Trolling through some old tweets, it looks like it might have last been run around _"7:37 AM · Aug 10, 2022"_, per https://twitter.com/eleven_ty/status/1557375465802842112
&hellip; and this didn't land until ~Aug 13.

**Comment by andystevenson** [comment]
Thanks Peter. That makes sense.
