### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by jasonbayton** [11ty/11ty-community#214]
### Site URL

https://bayton.org

### Source code URL

https://github.com/jasonbayton/11ty

**Comment by pdehaan** [comment]
:tada:
```html
<meta name="generator" content="Eleventy">
```

**Comment by jasonbayton** [comment]
Already there! Thank you!

**Comment by pdehaan** [comment]
**PROTIP:** There is also an `{{ eleventy.generator }}` variable which was added in Eleventy v1.0.1 that returns a fancy string like "Eleventy v1.0.2" (per https://www.11ty.dev/docs/data-eleventy-supplied/#eleventy-variable):

```js
  // For use with `<meta name="generator">`
  generator: "Eleventy v1.0.1", // New in Eleventy v1.0.1
```
