### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by kylepfeeley** [11ty/11ty-community#221]
### Site URL

https://www.kadotaproductions.com/

### Authors (GitHub usernames)

@kylepfeeley

### Open Collective Username

kylepfeeley

### Super Professional Business Network CTA URL

https://www.foxdog.io/

### Super Professional Business Network Company Name

Foxdog Collective

**Comment by pdehaan** [comment]
🎉 
```html
<meta name="generator" content="Eleventy">
```
