### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by stopnoanime** [11ty/11ty-community#223]
### Site URL

https://11ty-no-style-please.netlify.app/

### Source code URL

https://github.com/stopnoanime/11ty-no-style-please

### Authors (GitHub usernames)

@stopnoanime

**Comment by pdehaan** [comment]
@stopnoanime Not sure if you want to add this here, or add it to the https://www.11ty.dev/docs/starter/ page (via https://github.com/11ty/11ty-website/tree/main/src/_data/starters) if this is a starter template.

**Comment by stopnoanime** [comment]
You are right, I didn't see the starter templates page. I will add it there
