### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by mojoaxel** [11ty/11ty-community#225]
### Site URL

https://boffer.net/

### Source code URL

https://github.com/mojoaxel/boffer.net

### Authors (GitHub usernames)

@mojoaxel
@Bofferson

### Open Collective Username

mojoaxel

**Comment by pdehaan** [comment]
@mojoaxel Looks like the source code URL is 404ing for me (most likely a private repo).
We'd either want to make that a public repo, or remove the source code URL.
