### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by jabranr** [11ty/11ty-community#231]
### Site URL

https://www.local.com.pk

### Authors (GitHub usernames)

@jabranr

**Comment by pdehaan** [comment]
@jabranr I think we need to update the source code URL to be the website (not just the GitHub org).
Closest I could find to code was https://github.com/localpk/blog, but that looks like a Gatsby site.

**Comment by jabranr** [comment]
@pdehaan That is my bad actually. The source code is actually private for this at the moment so I just pointed to the org. If this is not compulsory then I am happy to remove it.

**Comment by pdehaan** [comment]
Yeah, probably better to remove it versus linking to generic org.
We can update the file later when/if you decide to make the repo public.

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v1.0.2">
```

**Comment by jabranr** [comment]
@pdehaan I have removed that from the OP now. Do I have to create a PR with these changes somewhere?
