### ISSUE TITLE
Brook Blog Starter Theme

### ISSUE THREAD

**Issue by holger1411** [11ty/11ty-community#236]
### Site URL

https://brooks-html-template.netlify.app/

### Source code URL

https://github.com/holger1411/brook-dev

### Authors (GitHub usernames)

@holger1411

### Super Professional Business Network Company Name

templatedeck.com

**Comment by pdehaan** [comment]
Also submitted as a starter template in https://github.com/11ty/11ty-website/pull/1472.
Once that lands, we might be able to close this.
