### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by Accudio** [11ty/11ty-community#281]
### Site URL

https://async-alpine.dev

### Open Collective Username

alistair-shepherd

**Comment by pdehaan** [comment]
Love me some Alpine.js!

**Comment by Accudio** [comment]
@pdehaan Eleventy 2 using the vite plugin, a great stack right there!

Unsurprisingly given the website I'm submitting I use a lot of Alpine.js—glad to hear you're a fan too!

Thanks!
