### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by mortendk** [11ty/11ty-community#286]
### Site URL

https://11tyhub.dev

### Source code URL

https://github.com/mortendk/11tyhub.dev

### Authors (GitHub usernames)

@mortendk

### Super Professional Business Network CTA URL

https://morten.dk

### Super Professional Business Network Company Name

theme machine

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v2.0.0">
```
