### ISSUE TITLE
[Built with Eleventy] I built something: https://github.com/xiyueuyix/11ty-starter-latex-blog

### ISSUE THREAD

**Issue by xiyueuyix** [11ty/11ty-community#299]
### Site URL

https://11ty-high-performance-latex-blog.euyix.me/

### Source code URL

https://github.com/xiyueuyix/11ty-high-performance-latex-blog

### Authors (GitHub usernames)

@xiyueuyix

**Comment by pdehaan** [comment]
> This site can’t be reached

**Comment by xiyueuyix** [comment]
Moved to <https://github.com/xiyueuyix/11ty-high-performance-latex-blog> <https://11ty-high-performance-latex-blog.euyix.me/>
