### ISSUE TITLE
[Built with Eleventy] Add brycewray.com

### ISSUE THREAD

**Issue by brycewray** [11ty/11ty-community#301]
### Site URL

https://www.brycewray.com

### Source code URL

https://github.com/brycewray/eleventy_site

### Open Collective Username

bryce-wray

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v2.0.0">
```

**Comment by brycewray** [comment]
> 😍
> 
> ```
> <meta name="generator" content="Eleventy v2.0.0">
> ```

Yep, I'm loving that thing so far. Just to use `eleventy.config.js` is cool on its own. 😄 Looking forward to the .19 beta with that `incremental` fix.

**Comment by brycewray** [comment]
@pdehaan Looks like I’ll need to withdraw (again 😞 ). Am not sure, but I’d rather be safe than sorry re the accuracy of Eleventy “Authors” list, the next edition of the leaderboard, *etc.*. Please delete the data for `brycewray.com`. My apologies! *(And if you would prefer I handle this via a separate issue, please let me know.)*

**Comment by pdehaan** [comment]
Yeah, probably easiest if you do a PR that removes https://github.com/11ty/11ty-community/blob/main/built-with-eleventy/yHM6-1qAlG.json (assuming that's the right site). And I can R+ and merge it.
Or I can do it later today if you prefer.

**Comment by brycewray** [comment]
> Yeah, probably easiest if you do a PR that removes https://github.com/11ty/11ty-community/blob/main/built-with-eleventy/yHM6-1qAlG.json (assuming that's the right site). And I can R+ and merge it. Or I can do it later today if you prefer.

PR submitted. Thanks!
