### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by davidmead** [11ty/11ty-community#327]
### Site URL

https://davidjohnmead.com

**Comment by pdehaan** [comment]
🎉 
```html
<meta name="generator" content="Eleventy">
```

**Comment by pdehaan** [comment]
FWIW, a broken image on the homepage:
![Screenshot 2023-01-08 at 11 33 10 AM](https://user-images.githubusercontent.com/557895/211215212-336b5d7d-eac2-4dbf-ae6e-466a8596389e.png)

**Comment by davidmead** [comment]
Thanks @pdehaan. I checked in an incognito tab and it's working for me. I am playing with new image file formats, and that is a `.jp2` file so may not be fully supported.
