### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by mattobee** [11ty/11ty-community#344]
### Site URL

https://mattobee.com

### Source code URL

https://github.com/mattobee/mocom11ty

### Open Collective Username

mattobee

**Comment by pdehaan** [comment]
@mattobee It looks like https://github.com/mattobee/mocom11ty is 404ing for me. Is it a private repo?

**Comment by pdehaan** [comment]
:tada:
```html
<meta name="generator" content="Eleventy">
```

**Comment by mattobee** [comment]
> @mattobee It looks like https://github.com/mattobee/mocom11ty is 404ing for me. Is it a private repo?

Fixed, sorry about that.
