### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by minamarkham** [11ty/11ty-community#347]
### Site URL

https://mina.codes/

### Source code URL

https://github.com/minamarkham/cupcake

**Comment by craigerskine** [comment]
This is amazing.

**Comment by pdehaan** [comment]
:tada:
```html
<meta name="generator" content="Eleventy">
```

**Comment by pdehaan** [comment]
I gotta say, this is probably the best use of git branches I've seen! 💯 ❤️
