### ISSUE TITLE
[Built with Eleventy] I built something: globe.church!

### ISSUE THREAD

**Issue by jamesdoc** [11ty/11ty-community#349]
### Site URL

https://www.globe.church

### Source code URL

https://github.com/theglobechurch/globe-static

### Authors (GitHub usernames)

@jamesdoc
@MazOneTwoOne

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v1.0.2">
```

**Comment by jamesdoc** [comment]
Thanks @pdehaan. Next weekend's job is to get that `1.0.2` to `2.0.0`
