### ISSUE TITLE
[Built with Eleventy] I built something! - statox.fr

### ISSUE THREAD

**Issue by statox** [11ty/11ty-community#36]
### Site URL

https://www.statox.fr/

### Exclude from Leaderboards?

- [ ] Excluded

### Source code URL

https://github.com/statox/blog/

**Comment by zachleat** [comment]
Good feedback, thank you!

I did note that this site already exists in our data set?

https://github.com/11ty/11ty-community/blob/edd2e56c45b66fe69fa0c34c93e06f114429f9f6/built-with-eleventy/YrI5z7ScXF.json

**Comment by statox** [comment]
:facepalm: Yes it was there already. The PR you commented on was me trying to add an `author` property my website to show on the author page. But now that you changed the page it already appears.

I just got excited to test the new flow, sorry for the noise.

**Comment by zachleat** [comment]
No worries at all! I appreciate you trying it out! 🙌🏻
