### ISSUE TITLE
Eleventy Authors links return error

### ISSUE THREAD

**Issue by sarhov** [11ty/11ty-community#394]
`"error": "Having trouble writing to \"false\" from \"...`

Having an issue trying to visit the author links in https://www.11ty.dev/authors/

![image](https://user-images.githubusercontent.com/1782362/221840236-7c72bad1-a027-445c-a821-15b5a5adebe6.png)

**Comment by pdehaan** [comment]
Looks like this was fixed. Thanks for the report! ❤️
