### ISSUE TITLE
[Built with Eleventy] Story Bot. AI Blog 

### ISSUE THREAD

**Issue by Bullrich** [11ty/11ty-community#412]
### Site URL

https://storybot.dev

### Source code URL

https://github.com/CodingBull-dev/Story-Bot/

### Open Collective Username

bullrich

**Comment by pdehaan** [comment]
🎉 
```html
<meta name="generator" content="Eleventy">
```

**Comment by pdehaan** [comment]
@Bullrich While looking for `meta[name=generator]` tags, i noticed you had some duplicated meta tags. Filed as https://github.com/CodingBull-dev/Story-Bot/issues/60
