### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by Bullrich** [11ty/11ty-community#413]
### Site URL

https://bullrich.dev

### Source code URL

https://github.com/Bullrich/bullrich.github.io

### Open Collective Username

bullrich

### Super Professional Business Network CTA URL

https://bullrich.dev

**Comment by pdehaan** [comment]
:tada:
```html
<meta name="generator" content="Eleventy">
```

**Comment by Bullrich** [comment]
Hi @pdehaan!

Seems that [the job failed](https://github.com/11ty/11ty-community/actions/runs/4566852158/jobs/8059914632)

```
Error: request to http://bullrich/ failed, reason: getaddrinfo EAI_AGAIN bullrich
```
Seems to be a network connectivity problem.

**Comment by pdehaan** [comment]
Ah, it was an invalid CTA URL. Fixed.
