### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by dijonkitchen** [11ty/11ty-community#421]
### Site URL

https://www.dijonkitchen.org/

### Source code URL

https://github.com/dijonkitchen/dijonkitchen.github.io

**Comment by pdehaan** [comment]
@dijonkitchen Is this an eleventy site? It looks like Jekyll.
```html
<meta name="generator" content="Jekyll v3.9.3">
```

**Comment by dijonkitchen** [comment]
Ah, I thought others could try to be on leaderboard. No worries.
