### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by Afif13** [11ty/11ty-community#433]
### Site URL

https://css-tip.com/

### Source code URL

https://github.com/Afif13/CSS-Tip

### Authors (GitHub usernames)

@Afif13

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v2.0.1">
```

**Comment by Afif13** [comment]
@pdehaan did you know why my website is still not listed here: https://www.11ty.dev/speedlify/ ?
