### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by KrishNotes** [11ty/11ty-community#437]
### Site URL

https://edukatte.netlify.app/

### Source code URL

https://github.com/KrishNotes/Krish-Notes

### Authors (GitHub usernames)

@KrishBeachoo 

### Open Collective Username

KrishBeachoo

### Super Professional Business Network CTA URL

https://edukatte.netlify.app/

### Super Professional Business Network Company Name

Edukatte

**Comment by pdehaan** [comment]
@KrishNotes Looks like https://github.com/KrishNotes/Krish-Notes is 404ing for me (usually means it's set to "private").
Not sure if you want to remove the source URL or make the repo public.
