### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by jbasoo** [11ty/11ty-community#442]
### Site URL

https://jamesbasoo.com/

### Source code URL

https://github.com/jbasoo/jamesbasoo

**Comment by pdehaan** [comment]
😍 
```html
<meta name="generator" content="Eleventy v2.0.1">
```

**Comment by jbasoo** [comment]
> 😍
> 
> ```
> <meta name="generator" content="Eleventy v2.0.1">
> ```

It's a nice touch having it in the default template but commented out. Easy opt-in!
