### ISSUE TITLE
[Built with Eleventy] The Personal Blog for Neal Gamradt

### ISSUE THREAD

**Issue by ngamradt** [11ty/11ty-community#453]
### Site URL

https://nealgamradt.com

**Comment by ngamradt** [comment]
Just a note that I do plan to release an open source boilerplate repository with my GitOps solution for getting an 11ty site deployed on AWS.  This will be part of my ["Blog on a Budget" series](https://nealgamradt.com/posts/2023/06/blog-on-a-budget-overview/index.html).

One of my latest posts for my "Blog on a Budget" series is about [why I picked 11ty for my blog](https://nealgamradt.com/posts/2023/07/choosing-a-jamstack/index.html).  If you don't mind, please take a look and let me know if you have any thoughts or feedback (good or bad).

Thanks for such a great product!

**Comment by pdehaan** [comment]
🎉 
```html
<meta name="generator" content="Eleventy">
```

**Comment by ngamradt** [comment]
Hello @pdehaan, thank you for approving this submission.  Does this mean my site will likely show up on the following page at some point?

https://www.11ty.dev/speedlify/

**Comment by pdehaan** [comment]
@ngamradt That's the theory. I'm not sure if the leaderboard regeneration is still a manual process or not though. @zachleat is the one that maintains all that pipeline.

From the looks of the results, the last deployed update might have been around Apr 13, 2023.
