### ISSUE TITLE
[Built with Eleventy] Frontend Dogma

### ISSUE THREAD

**Issue by j9t** [11ty/11ty-community#468]
### Site URL

https://frontenddogma.com/

### Open Collective Username

frontenddogma

**Comment by pdehaan** [comment]
@j9t Same w/ this site. Not sure if you want to make the repo public, or just remove the link.

**Comment by j9t** [comment]
@pdehaan, documented the repository URL if there is need for anyone to verify use of Eleventy. For Frontend Dogma, the repository used to be public and I may make it public again, but that’s still TBD. If the URL is not needed, I can remove it, sure.
