### ISSUE TITLE
[Built with Eleventy] WebGlossary.info

### ISSUE THREAD

**Issue by j9t** [11ty/11ty-community#469]
### Site URL

https://webglossary.info/

**Comment by pdehaan** [comment]
@j9t Looks like the repo is private. Did you want to make it public, or just remove the linked "Source code URL"?

**Comment by j9t** [comment]
@pdehaan, documented the repository URL if there is need for anyone to verify use of Eleventy. For WebGlossary.info, I don’t currently plan to make the repository public. If the URL is not needed, I can remove it, sure.
