### ISSUE TITLE
[Built with Eleventy] I built my website!

### ISSUE THREAD

**Issue by njfamirm** [11ty/11ty-community#471]
### Site URL

https://njfamirm.ir/

### Source code URL

https://github.com/njfamirm/njfamirm.ir

### Authors (GitHub usernames)

@njfamirm, @AliMd for base of my website

**Comment by njfamirm** [comment]
Thanks for creating eleventy 💎

**Comment by njfamirm** [comment]
wtf 😂, author....

**Comment by pdehaan** [comment]
@njfamirm Sorry, my fault, I didn't see all the extra text in authors field.
you can submit a PR for https://github.com/11ty/11ty-community/blob/main/built-with-eleventy/2Sq1660bTs.json if you want to remove the extra stuff, otherwise I can PR it later today.

**Comment by pdehaan** [comment]
Nevermind, I didn't scroll my emails far enough, I see you had a PR already at #476

**Comment by njfamirm** [comment]
I apologize for not reading the document carefully, thank you
