### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by KhoiUna** [11ty/11ty-community#488]
### Site URL

https://blog.khoiuna.info/

### Source code URL

https://github.com/KhoiUna/my-blog

### Open Collective Username

khoiuna

**Comment by pdehaan** [comment]
🎉 
```html
<meta name="generator" content="Eleventy">
```

**Comment by KhoiUna** [comment]
@pdehaan Where can I view it on the 11ty site?
