### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by hryggrbyr** [11ty/11ty-community#512]
### Site URL

https://thomasrigby.com/

### Open Collective Username

@hryggrbyr

**Comment by Snapstromegon** [comment]
Hey @hryggrbyr,
thanks for contributing. Sadly it seems like your source code repo is unavailable (maybe it's private).
A repo that is private doesn't help the community to learn, so I would suggest to either make it public or (if you don't want to do that) remove the source code url from this issue to avoid confusion.

**Comment by hryggrbyr** [comment]
Ah, thanks! I've removed it for now.
