### ISSUE TITLE
BeCSS

### ISSUE THREAD

**Issue by iturbides** [11ty/11ty-community#525]
### Site URL

https://www.becss.dev

### Authors (GitHub usernames)

@iturbides

**Comment by Snapstromegon** [comment]
Hey @iturbides,
thanks for your submission, but I think there is some issue with your issue.
The source code url you provided points to the repo for becss, but this field is meant for the repo holding the code for becss.dev. Looking through your repos, this seems to be this repo: https://github.com/iturbides/starter-eleventy
Maybe you want to rename that repo to something more meaningful and update this issue.
Also to note: becss.dev right now does not fit the requirements to be placed on the 11ty leaderboards, as it doesn't include a `<meta name="generator" content="Eleventy">` (if I see correctly).

**Comment by iturbides** [comment]
Hello @Snapstromegon, I am afraid I have misunderstood the purpose of this field. Sorry. I have deleted the data and added the "generator" tag. Thank you!
 I'm sorry for my confusion, I'm very clumsy with github.
