### ISSUE TITLE
[Built with Eleventy] TapChamps.com

### ISSUE THREAD

**Issue by hakim-d** [11ty/11ty-community#540]
### Site URL

https://tapchamps.com/

**Comment by Snapstromegon** [comment]
Hey @hakim-d,
the field "Source code URL" is meant for "The URL to the public repository for the source code for this site.". So placing typchamps there is not correct.

FYI: the page you're submitting doesn't have a generator meta tag, so it's not eligible for the Eleventy Leaderboards.

**Comment by zachleat** [comment]
Just for future reference, meta generator is not required to be added here! It just can’t be set to something other than Eleventy
