### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by teotimepacreau** [11ty/11ty-community#589]
### Site URL

https://www.teotimepacreau.fr/

### Source code URL

https://github.com/teotimepacreau/Personal-website

**Comment by Snapstromegon** [comment]
@zachleat It seems like the GitHub action for this one failed. (https://github.com/11ty/11ty-community/actions/runs/8261103923)
I don't see why it failed right away, maybe you know what's wrong there?
