### ISSUE TITLE
TDH.se

### ISSUE THREAD

**Issue by tdhftw** [11ty/11ty-community#603]
### Site URL

https://tdh.se

### Authors (GitHub usernames)

@tdhftw

**Comment by zachleat** [comment]
Reverted this one in 614d495fe2fecd3f13a3fa185fcd560064b2a9d0

**Comment by tdhftw** [comment]
Ah, sorry about that, should've remembered that the site migrated. Still loving Eleventy though, [Bored Horse](https://bored.horse) is on it (and TDH.se might be again soon).
