### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by isobolewski** [11ty/11ty-community#61]
### Site URL

https://www.sobolewski.cz

### Open Collective Username

isobolewski

### Super Professional Business Network CTA URL

https://www.sobolewski.cz

### Super Professional Business Network Company Name

Ingo Sobolewski | web-engineering

**Comment by pdehaan** [comment]
Thanks @isobolewski

**Comment by isobolewski** [comment]
Is it possible to get added to the SUPER PROFESSIONAL BUSINESS NETWORK? Monthly $5 donation was made.

**Comment by isobolewski** [comment]
> /cc @zachleat since I'm just a monkey who adds labels and merges PRs.

Thanks for redirect!

**Comment by zachleat** [comment]
@isobolewski it should be automatic! If the daily build doesn’t pick this up (usually because your opencollective username is mismatched—check back in 24h), please file an issue and I’ll have a look!

**Comment by isobolewski** [comment]
> @isobolewski it should be automatic! If the daily build doesn’t pick this up (usually because your opencollective username is mismatched—check back in 24h), please file an issue and I’ll have a look!

@zachleat Thanks, it could be that the opencollective username was created with delay, probably my fault :-( but its there https://opencollective.com/isobolewski

**Comment by isobolewski** [comment]
@zachleat In the meantime I got listed in the authors page, but unfortunately the link to my Eleventy generated website to receive Business contacts does not work (Page not found) see here -> https://www.11ty.dev/authors/isobolewski/

Is there a change to fix it? I am eager to get some work around Eleventy...

**Comment by zachleat** [comment]
Fixed!
