### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by lordvalor** [11ty/11ty-community#707]
### Site URL

https://elrastrillo.pe/

**Comment by Snapstromegon** [comment]
Hi @lordvalor, the repo you link seems to be private.
Since the repo links are meant to be inspiration for other users I'd like to ask you to either make it public if it's supposed to be public, or remove the link from your issue (both options are totally fine).

**Comment by lordvalor** [comment]
Hi, unfortunately I can not put it public because it is for a client, I have no authorization, but I have no problem in removing the issue and then I will do it with another that if it can be published. 

Sorry for the inconvenience. 
Thank you very much.

**Comment by Snapstromegon** [comment]
Having the site listet at all is already awesome, so thanks for submitting and showing off what's possible!
