### ISSUE TITLE
[Built with Eleventy] I built something!

### ISSUE THREAD

**Issue by mwt** [11ty/11ty-community#745]
### Site URL

https://www.matthewthom.as

### Source code URL

https://github.com/mwt/matthewthomas-11ty/

### Open Collective Username

mwt

**Comment by Snapstromegon** [comment]
Hey, just a note: You're still setting Jekyll as your generator:
https://github.com/mwt/matthewthomas-11ty/blob/main/src/_includes/tools/seo.liquid#L6
