### ISSUE TITLE
AaronMorey.com

### ISSUE THREAD

**Issue by aaronmfmorey** [11ty/11ty-community#747]
### Site URL

https://aaronmorey.com

**Comment by Snapstromegon** [comment]
Hey @aaronmfmorey,
it seems like your repository is private.

This field is meant to allow others to take a peak at how you implemented the page. If you don't want to share your source (which is totally fine), please replace the source code url with the default answer again.

**Comment by aaronmfmorey** [comment]
Sorry about that. I'm not ready to open it up right now, so I removed the link.
