### ISSUE TITLE
For Leaderboards

### ISSUE THREAD

**Issue by sarhov** [11ty/11ty-community#770]
https://cro.media

**Comment by sarhov** [comment]
cro.media is already in built with 11ty, but it never appeared in leaderboards, so I though maybe I need to submit it in separate issue.

**Comment by Snapstromegon** [comment]
Hey @sarhov,
Zach runs the leaderboard manually from time to time (last run was in March, I don't know when the next one will be).
Your site will show up in the next run.
Sorry that this is not a fast process and that the insight is very limited.
