### ISSUE TITLE
What should happen to the budget available in the Open-Collective 11ty account?

### ISSUE THREAD

**Issue by johanbove** [11ty/11ty-community#78]
Was wondering about the open-collective account for 11ty. I've been personally contributing for a while, amongst other people; but haven't seen any re-use of the cash in the account. Why hasn't there been?

cf. [https://opencollective.com/11ty](https://t.co/hltCX4EG34)

💡11ty has a neat bunch of dependencies that could use some support.

**Comment by pdehaan** [comment]
I vote for spending it on custom possum themed adidas track suits for @zachleat.
Possibly a matching [casual Kangol Furgora](https://www.ebay.ca/itm/334368084577?hash=item4dd9e41261:g:Ws0AAOSwA81iM0O3), budget permitting.
I think he could pull it off as his new "signature look". 🤷

**Comment by johanbove** [comment]
Could start by checking which of these are struggling?

```bash
11ty
├── https://github.com/sponsors/sindresorhus
│   └── hasha@5.2.2, is-stream@2.0.1, @sindresorhus/slugify@1.1.2, @sindresorhus/transliterate@0.1.2, escape-string-regexp@4.0.0, multimatch@5.0.0, get-stdin@8.0.0, globby@11.1.0, meow@9.0.0, type-fest@0.18.1, import-fresh@3.3.0, open@8.4.0, terminal-link@2.1.1, ansi-escapes@4.3.2, type-fest@0.21.3, boxen@5.1.2, camelcase@6.3.0, cli-boxes@2.2.1, type-fest@0.20.2, is-installed-globally@0.4.0, global-dirs@3.0.0, is-npm@5.0.0, make-dir@3.1.0, is-docker@2.2.1, decompress-response@6.0.0, mimic-response@3.1.0, get-stream@5.2.0, normalize-url@6.1.0, quick-lru@5.1.1, meow@7.1.1, camelcase-keys@6.2.2, map-obj@4.3.0, read-pkg-up@7.0.1, p-limit@2.3.0, parse-json@5.2.0, type-fest@0.13.1, is-finite@1.1.0
├─┬ https://opencollective.com/11ty
│ │ └── @11ty/eleventy@1.0.0, @11ty/eleventy-plugin-rss@1.1.2, @11ty/eleventy-plugin-syntaxhighlight@3.1.3
│ ├── https://opencollective.com/liquidjs
│ │   └── liquidjs@9.32.0
│ ├── https://opencollective.com/ua-parser-js
│ │   └── ua-parser-js@1.0.2
│ ├── https://github.com/sponsors/jonschlinkert
│ │   └── picomatch@2.3.1
│ ├── https://github.com/sponsors/feross
│ │   └── run-parallel@1.2.0, queue-microtask@1.2.3, arch@2.2.0, safe-buffer@5.2.1, buffer@6.0.3, base64-js@1.5.1, ieee754@1.2.1, is-buffer@2.0.5
│ ├── https://github.com/fb55/entities?sponsor=1
│ │   └── entities@2.1.0, entities@2.2.0, entities@3.0.1
│ ├── https://github.com/sponsors/isaacs
│ │   └── glob@7.2.0, rimraf@3.0.2
│ └── https://github.com/sponsors/ljharb
│     └── is-regex@1.1.4, call-bind@1.0.2, get-intrinsic@1.1.1, has-symbols@1.0.2, has-tostringtag@1.0.0, resolve@1.21.0, is-core-module@2.8.1, supports-preserve-symlinks-flag@1.0.0
├─┬ https://opencollective.com/stylelint
│ │ └── stylelint@14.2.0
│ ├── https://github.com/sponsors/epoberezkin
│ │   └── ajv@8.8.2, ajv@6.12.6
│ └── https://github.com/chalk/slice-ansi?sponsor=1
│     └── slice-ansi@4.0.0
├─┬ https://github.com/chalk/chalk?sponsor=1
│ │ └── chalk@4.1.2
│ └── https://github.com/chalk/ansi-styles?sponsor=1
│     └── ansi-styles@4.3.0
├── https://github.com/yeoman/update-notifier?sponsor=1
│   └── update-notifier@5.1.0
├── https://github.com/sponsors/RubenVerborgh
│   └── follow-redirects@1.14.7
├─┬ https://github.com/sindresorhus/got?sponsor=1
│ │ └── got@11.8.3
│ └── https://github.com/sindresorhus/is?sponsor=1
│     └── @sindresorhus/is@4.2.1
├── https://github.com/sponsors/wooorm
│   └── mathml-tag-names@2.1.3, collapse-white-space@1.0.6, is-alphabetical@1.0.4, is-decimal@1.0.4, is-whitespace-character@1.0.4, is-word-character@1.0.4, markdown-escapes@1.0.4, state-toggle@1.0.3, trim-trailing-lines@1.1.4, unherit@1.1.3, character-entities@1.2.4, character-entities-legacy@1.1.4, character-reference-invalid@1.1.4, is-alphanumerical@1.0.4, is-hexadecimal@1.0.4, ccount@1.1.0, longest-streak@2.0.4, character-entities-html4@1.1.4, bail@1.0.5, trough@1.0.5
├── https://opencollective.com/browserslist
│   └── caniuse-lite@1.0.30001299, browserslist@4.19.1
├── https://opencollective.com/postcss/
│   └── postcss@7.0.39, postcss-safe-parser@6.0.0
├── https://opencollective.com/unified
│   └── unist-util-find-all-after@1.0.5, unist-util-remove-position@1.1.4, vfile-location@2.0.6, mdast-util-compact@1.0.4
├── https://tidelift.com/funding/github/npm/autoprefixer
│   └── autoprefixer@9.8.8
└── https://opencollective.com/babel
    └── @babel/core@7.16.7
```

**Comment by pdehaan** [comment]
> Idea would be to find that one person in Nebraska who could use some support: cf. [xkcd.com/2347](https://xkcd.com/2347/)

Wait, isn't @zachleat in Nebraska? /quickly checks how long he has been maintaining 11ty!

<kbd>npm info @11ty/eleventy time.created # 2018-01-09T14:36:27.855Z</kbd>

**Comment by johanbove** [comment]
Case settled then.

**Comment by zachleat** [comment]
Just as disclosure this question was discussed on JSParty!
* https://twitter.com/eleven_ty/status/1509903095970607121
* https://changelog.com/jsparty/217

Quoting from the transcript:

> Yeah, that’s valid criticism. I don’t really feel like I have a great story for that. I feel like the other side of the coin is that some of these projects are better about maintainers removing the funds and not really telling a good story about what the funds are being used for. There’s a lot of trust that goes into donating to an open source project, and I would say that I haven’t seen too many folks cancel their Open Collective contributions… Because I do really want folks to understand that it is an investment in the longevity of the project. So I don’t consider this Netlify arrangement to be something that will probably exist for ten years. I mean, if it did, that would be awesome, but I think if we’re all honest, I don’t think that that will be a thing that will exist in ten years.

> That is kind of a fallback strategy for me at this point, and I’m open to discussing it with folks if they have concerns about that. But I do feel that my mindset is changing a little bit with this new arrangement at Netlify, and I’ll probably start to use the money in a more community-organized way moving forward, as I feel more comfortable with the arrangement moving forward. 

All that said, I absolutely would upvote some funding to `liquidjs` and `sindresorhus`.

**Comment by zachleat** [comment]
11ty is now a backer of liquidjs https://opencollective.com/liquidjs

**Comment by pdehaan** [comment]
Fun idea... Here's a snippet from Sara Soueidan's [Practical Accessibility](https://practical-accessibility.today/) latest newsletter update:

> Over this past year, my progress on the course was a bit slower than I wanted it to be. I'm a freelancer, and since **this course is not currently sponsored**, the time I spend working on it takes away from my time working on client projects. &hellip;
>
>As some of you may know, I am using [Eleventy](http://mail01.tinyletterapp.com/SaraSoueidan/an-overdue-practical-accessibility-course-update/21015113-11ty.dev/?c=a1820314-746d-44e4-bd71-856c28969aaf) to create the course Web site. I chose not to use a course platform because of accessibility as well as flexibility and customizability limitations. There were also limitations related to things like payment portals, most of which don’t work for someone living in Lebanon.
>
> With the custom site I built, I have full control over everything — content, layout, design, and everything in between. (I am considering releasing the site as an 11ty template after the course is finished!)

11ty could become a/the official sponsor for the Practical Accessibility premium course. 

Free tagline: 11ty :heart: a11y

**Comment by zachleat** [comment]
cc @SaraSoueidan can you send over options for that? is sponsorship still available?

**Comment by Zearin** [comment]
Love @SaraSoueidan’s work. Before #a11y her articles taught me so much about #SVG. She’s a _fantastic_ teacher. And she’s very indie-web—very aligned with 11ty. 

Great choice.

**Comment by rdela** [comment]
This could probably be closed now between https://www.11ty.dev/blog/sustainability-fundraising/ + https://conf.11ty.dev 

As foretold by Johan, [Zach’s 11ty Conf talk appropriately contained](https://youtu.be/tXNsWsEE7S0?t=76) the [XKCD 2347](https://xkcd.com/2347/) reference. (Someday Eleventy will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble.)

**Comment by rdela** [comment]
There was also some funny discussion of XKCD 2347 at the end of https://changelog.com/jsparty/325 👏 @nicknisi + @jerodsanto

**Comment by zachleat** [comment]
Thank you @rdela!
